### ISSUE TITLE
ES6 Modules

### ISSUE THREAD

**Issue by brettz9** [WebReflection/query-result#2]
I'm finally looking into possibly giving this a try, but I'd like to see an ES6 module export (not only in source, but also distributed, as with Rollup and `module` in `package.json`)... Are you still maintaining?

**Comment by WebReflection** [comment]
I admittedly forgot about this module, which is kinda a shame 'cause it's handy indeed.

However, I don't have much time, nor interest, in changing its basic "beauty" and functionality, but I do agree a modern ESM version of the idea should land in npm ... which just did.

You can load the modern ESM version of this lib via `esm/index.js` also specified as module.

Watch out, most transpilers targeting browsers incapable of ES2015 will fail in transpiring this module correctly, the ESM version is indeed how the ideal, native, untranspiled world, should work.

Hope this is OK for the time being, will clean the rest up whenever I find some extra time.

**Comment by brettz9** [comment]
This is great, thanks very much!

I am very eager to play around with it...

While I know you said you don't want to change the functionality, I'd like to offer just one suggestion though for what seems to me a pretty fundamental need (and which may be useful to extendors as well):

```js
  $.extend('each', function (cb, thisObj) {
    this.forEach(cb, thisObj);
    return this;
  });
```

(since the regular `forEach` doesn't return anything useful, I suppose you could override it, but but such an important method, `each` is nice and short and it might seem non-intuitive to chain `forEach` anyways.)

**Comment by WebReflection** [comment]
that's the reason you have `$.extend` so that you put in whatever you want.

`each` is historically controversial because jQuery had the forEach signature upside down (key before value) so having in core something misleading is not interesting.

Again, this library is great because it lets you extend it the way you prefer. If you don't like that mechanism , don't use this library 'cause I won't accept any extra extend in here ever.

Feel free to create modules that import this library and extend it as they wish though, that's why extend is there (and also why all methods are configurable, so you can even redefine the most basic de-facto standard tools in place such `on`, `off`, and `dispatch`, if needed).

**Comment by WebReflection** [comment]
P.S. use `.map(...)` if you want to play around with the result, but remember to return each value

**Comment by brettz9** [comment]
Gotcha...

**Comment by brettz9** [comment]
Starting with this... https://github.com/brettz9/qr-manipulation / https://www.npmjs.com/package/qr-manipulation ... Will see how far it goes...

**Comment by WebReflection** [comment]
> Not yet supporting arrays or QueryResult objects

that's actually a valid point, you have no easy way to understand if an object is an instance of QueryResult. Any suggestion? That's something I can expose, without exposing the class itself, for security reasons.

**Comment by brettz9** [comment]
What about [`Symbol.hasInstance`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance) duck-typing for some combo of `dispatch`, `off`, `on`, and/or array methods/properties (e.g., numeric length)?
